// Generated by JniWriter, do not edit!
@file:Suppress("unused", "UNUSED_PARAMETER", "UnnecessaryVariable")

package com.birbit.sqlite3.internal

import com.birbit.jni.JNIEnvVar
import com.birbit.jni.jboolean
import com.birbit.jni.jclass
import com.birbit.jni.jint
import com.birbit.jni.jlong
import com.birbit.jni.jstring
import kotlin.Suppress
import kotlin.native.CName
import kotlinx.cinterop.CPointer

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeOpenConnection")
fun openConnection(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jstring
): jlong {
  initPlatform()
  val localP0 = checkNotNull(p0.toKString(env))
  val callResult = SqliteApi.openConnection(localP0)
  val localCallResult = callResult.toJni()
  return localCallResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativePrepareStmt")
fun prepareStmt(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong,
  p1: jstring
): jlong {
  initPlatform()
  val localP0 = DbRef.fromJni(p0)
  val localP1 = checkNotNull(p1.toKString(env))
  val callResult = SqliteApi.prepareStmt(localP0, localP1)
  val localCallResult = callResult.toJni()
  return localCallResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeStep")
fun step(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong
): ResultCode {
  initPlatform()
  val localP0 = StmtRef.fromJni(p0)
  val callResult = SqliteApi.step(localP0)
  return callResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeColumnText")
fun columnText(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong,
  p1: jint
): jstring? {
  initPlatform()
  val localP0 = StmtRef.fromJni(p0)
  val callResult = SqliteApi.columnText(localP0, p1)
  val localCallResult = callResult?.toJString(env)
  return localCallResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeColumnInt")
fun columnInt(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong,
  p1: jint
): jint {
  initPlatform()
  val localP0 = StmtRef.fromJni(p0)
  val callResult = SqliteApi.columnInt(localP0, p1)
  return callResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeColumnIsNull")
fun columnIsNull(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong,
  p1: jint
): jboolean {
  initPlatform()
  val localP0 = StmtRef.fromJni(p0)
  val callResult = SqliteApi.columnIsNull(localP0, p1)
  val localCallResult = callResult.toJBoolean()
  return localCallResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeReset")
fun reset(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong
): ResultCode {
  initPlatform()
  val localP0 = StmtRef.fromJni(p0)
  val callResult = SqliteApi.reset(localP0)
  return callResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeClose")
fun close(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong
): ResultCode {
  initPlatform()
  val localP0 = DbRef.fromJni(p0)
  val callResult = SqliteApi.close(localP0)
  return callResult
}

@CName("Java_com_birbit_sqlite3_internal_SqliteApi_nativeFinalize")
fun finalize(
  env: CPointer<JNIEnvVar>,
  clazz: jclass,
  p0: jlong
): ResultCode {
  initPlatform()
  val localP0 = StmtRef.fromJni(p0)
  val callResult = SqliteApi.finalize(localP0)
  return callResult
}
